files:
  - source: /Nos/Assets/Localization/Localizable.xcstrings
    dest: /Nos/Assets/Localization/Localizable.xcstrings
    translation: %original_path%/%original_file_name%
    multilingual: true
