"preserve_hierarchy": true
"files": [{
    "source": "Nos/Assets/Localization/Localizable.xcstrings", 
    "translation": "main/Nos/Assets/Localization/Localizable.xcstrings", 
    "download_translations_args": "--dest=Nos/Assets/Localization/Localizable.xcstrings",
    "multilingual": true 
}]
