"files": [{
    "source": "Nos/Assets/Localization/Localizable.xcstrings", 
    "translation": "Nos/Assets/Localization/Localizable.xcstrings", 
    "dest" : "Nos/Assets/Localization/Localizable.xcstrings",
    "multilingual": true 
}]
