"preserve_hierarchy": true
"files": [{
    "source": "Nos/Assets/Localization/*.xcstrings", 
    "translation": "Nos/Assets/Localization/%original_file_name%.xcstrings", 
    "multilingual": true 
}]
