"preserve_hierarchy": true
"files": [
    {
        "source": "Nos/Assets/Localization/*.xcstrings", 
        "translation": "%original_path%/%original_file_name%",
        "multilingual": true 
    }
]
